### ISSUE TITLE
Paused thermostats shown as heating

### ISSUE THREAD

**Issue by maverick-79** [MTrab/danfoss_ally#12]
Hi there,

It seems that thermostats which have been paused in the Danfoss app are shown as heating in HA.

The API returns the following, with the `mode` being shown as `pause`
```YAML
{
  "result": {
    "active_time": 1613145159,
    "create_time": 1613145159,
    "id": <id>,
    "name": "Bad",
    "online": true,
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "mode",
        "value": "pause"
      },
      {
        "code": "temp_set",
        "value": 220
      },
      {
        "code": "upper_temp",
        "value": 250
      },
      {
        "code": "temp_current",
        "value": 166
      },
      {
        "code": "window_state",
        "value": "close"
      },
      {
        "code": "lower_temp",
        "value": 60
      },
      {
        "code": "child_lock",
        "value": true
      },
      {
        "code": "battery_percentage",
        "value": 81
      },
      {
        "code": "factory_reset",
        "value": false
      },
      {
        "code": "fault",
        "value": 0
      }
    ],
    "sub": true,
    "time_zone": "+08:00",
    "update_time": 1639959199,
    "device_type": "Danfoss Ally™ Radiator Thermostat"
  },
  "t": 1643277875654
}
```
The same device is shown as having the following state attributes in HA, `hvac_action` being `heating` instead of `paused`:
```YAML
hvac_modes:
  - heat
min_temp: 6
max_temp: 25
target_temp_step: 0.5
current_temperature: 16.5
temperature: 22
hvac_action: heating
friendly_name: Bad
supported_features: 1
``` 
I guess the `mode` information is ignored in HA and `heating` is taken as default `hvac_action` based on the temperature difference?
In addition, would be great to be able to change `mode` directly from within HA (values seem to be `paused`, `at_home` and `leaving_home`).
